/* Automatically generated by './build/bin/build-entry.js' */

import Input from '../packages/input/index.js';
import InputNumber from '../packages/input-number/index.js';
import Radio from '../packages/radio/index.js';
import RadioGroup from '../packages/radio-group/index.js';
import RadioButton from '../packages/radio-button/index.js';
import Checkbox from '../packages/checkbox/index.js';
import CheckboxButton from '../packages/checkbox-button/index.js';
import CheckboxGroup from '../packages/checkbox-group/index.js';
import Select from '../packages/select/index.js';
import Option from '../packages/option/index.js';
import OptionGroup from '../packages/option-group/index.js';
import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';
import Table from '../packages/table/index.js';
import Tag from '../packages/tag/index.js';
import TableColumn from '../packages/table-column/index.js';
import Form from '../packages/form/index.js';
import FormItem from '../packages/form-item/index.js';
import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';
import Aside from '../packages/aside/index.js';
import Main from '../packages/main/index.js';
import InfiniteScroll from '../packages/infinite-scroll/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import Backtop from '../packages/backtop/index.js';
import Icon from '../packages/icon/index.js';
import Autocomplete from '../packages/autocomplete/index.js';
import locale from 'urpt-ui/src/locale';
import CollapseTransition from 'urpt-ui/src/transitions/collapse-transition';

const components = [
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  Tag,
  TableColumn,
  Form,
  FormItem,
  Row,
  Col,
  Aside,
  Main,
  Scrollbar,
  Backtop,
  Icon,
  Autocomplete,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(InfiniteScroll);

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  Tag,
  TableColumn,
  Form,
  FormItem,
  Row,
  Col,
  Aside,
  Main,
  InfiniteScroll,
  Scrollbar,
  Backtop,
  Icon,
  Autocomplete
};
